server:
  port: 8761

spring:
  application:
    name: ingredient-service
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false